# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # ğŸŒ Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  # ğŸ’¡ The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    
     -  name: ğŸ¦‘ Left
        uses: lowlighter/metrics@latest
        with:
          filename: right.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, starts, topics
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_stars: yes
          plugin_stars_limit: 3
          token:  ${{ secrets.GH_TOKEN }}

          
     -  name: ğŸ¦‘ Rihgt
        uses: lowlighter/metrics@latest
        with:
          config_order: anilist, steam
          filename: assets/right.svg
          base: ""
          plugin_anilist_user: "canisminor1990"
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "076561198054835207"
          plugin_steam_achievements_limit: 0
          token:  ${{ secrets.GH_TOKEN }}
